### ISSUE TITLE
Gif compression problem

### ISSUE THREAD

**Issue by CONOR007** [fengyuanchen/compressorjs#173] opened 2023-05-10 06:17 UTC
**Describe the bug**
After compressing the gif image, it becomes a png

**Expected behavior**
Hope to compress gif

**Additional context**
Does not support compression of gif image format?

**Comment by fengyuanchen** [comment] 2023-05-21 08:31
Duplicate of #78.

**Closed as completed by fengyuanchen** 2023-05-21 08:31 UTC
